name: conductor
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9,<3.13
  - jinja2
  - pydantic
  - gitpython
  - click
  - pygls
  - lsprotocol
  - ruff
  - mypy
  - pytest
  - pytest-cov
  - pyyaml
  - tomli
  - pip
  - pip:
    - PyGithub
    - types-PyYAML
